# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalCaptionsPro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenCaptionsMaker
  pod 'Firebase/Core'
  #pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'
  #pod 'Firebase/Messaging'
  pod 'AEXML'  # for XML handling
  pod 'HotKey'  # for MacOS keyboard shortcuts. This caused dependency issues with FBLPromises in Google Utilities
  #pod 'KeyboardShortcuts'  # for MacOS keyboard shortcuts

  target 'FinalCaptionsProTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinalCaptionsProUITests' do
    # Pods for testing
  end

end
